version: '2.1'
services:
  discovery:
    container_name: discovery
    image: markoniemi/discovery
    build: discovery
    ports:
      - 8761:8761
    networks:
      - microservice-example
  config:
    container_name: config
    image: markoniemi/config-server
    build: config-server
    ports:
      - 8081:8081
    networks:
      - microservice-example
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery:8761/eureka/
    depends_on:
      discovery:
        condition: service_healthy
  user-repository:
    container_name: user-repository
    image: markoniemi/user-repository
    build: user-repository
    ports:
      - 8082:8082
    links:
      - config:config
    networks:
      - microservice-example
    environment:
      - SERVICE_URL_DEFAULT_ZONE=http://discovery:8761/eureka/
    depends_on:
      config:
        condition: service_healthy
networks:
  microservice-example:
